language:
  - elixir

elixir:
  - 1.5.1

otp_release:
  - 20.0

sudo: false

cache:
  directories:
    - .dialyzer

script:
  - mix test
  - env MIX_ENV=test mix coveralls.travis
  - mix credo --strict
  - mix dialyzer
